### ISSUE TITLE
error

### ISSUE THREAD

**Issue by suciuale** [XanOpiat/Python-CSGO-Cheat#97]
![image](https://user-images.githubusercontent.com/30433247/150408100-9d42f83d-674c-4db2-8f89-939fb0008e2e.png)

**Comment by XanOpiat** [comment]
Did you call the script the right way?
because normally you need to type "python ProjectX_V2.py"
not just "ProjectX_V2.py"

but if i am missing something here, please tell me

**Comment by XanOpiat** [comment]
ok it looks like python cant find the pyqt dlls. 
This is most likely caused by the how you installed the library.

Here are some steps id recommend:
1. Reinstall the package using pip:
pip uninstall pyqt5
pip install pyqt5

2. If step 1 fails: Add the path to the pyqt5 binaries to path:
Find where pyqt5 is installed (Ie. something like "C:\....\
Type "edit system variables into the windows search bar"
Go to the advanced tab and hit "Environment Variables"
Then click edit, click new and paste in the install location of pyqt5
Hit ok.

**Comment by XanOpiat** [comment]
You could also try installing 64bit python from [here](python.org/downloads)

![Git](https://user-images.githubusercontent.com/62156037/150415774-d18e59a6-cd65-4fa4-94ff-c2606f02322c.png)

**Comment by suciuale** [comment]
solved it. seems like one of my hdd's is on its way out and it corrupted some data. thx for help

**Comment by XanOpiat** [comment]
np :D
